### ISSUE TITLE
Push docker image to docker hub

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/ion#51]
The readme builds a docker image locally. We can create a docker hub account and push it there.

**Comment by HarryR** [comment]
Support for Docker builds was added back in the pull request https://github.com/clearmatics/ion/pull/74

There are two versions of the Docker image:

 * Alpine + static PyInstaller executable (about 45mb total)
 * Alpine Python + standard python project etc. (more than 45mb... I think)

The PyInstaller executable version doesn't play well with automatic Docker builds because the `dist/ion` static executable is built outside of Docker... the other one should work fine though with automagic docker builds.

If in doubt, probably best to use the second one, I will have a look at this when it comes time to package & distribute stuff.

**Comment by HarryR** [comment]
See https://ops.tips/blog/travis-ci-push-docker-image/

The Travis CI build file I added can auto-push to Docker after building the image using PyInstaller. It needs the encrypted `DOCKER_USERNAME` and `DOCKER_PASSWORD` environment variables defined in your Travis CI config (please, don't put these in the `.travis.yml` file, that's dumb)
